export const constant = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  success: "success",
  CART_ADD: "CART_ADD",
  CART_REMOVE: "CART_REMOVE",
  CART_UPDATE: "CART_UPDATE",
  CART_GET: "CART_GET",
  ORDER_ADD: "ORDER_ADD",
};
